### ISSUE TITLE
External Link

### ISSUE THREAD

**Issue by LordVitor** [archriss/react-native-display-html#4]
Hi, 

How open external links ?
 like Linking.openURL(url)

**Comment by Exilz** [comment]
You have to inject javascript to handle it.
What I do is that I have a little snippet called `interceptLinks` that add a listener on each `<a>` that dispatches an action from the webview to the JS realm of react-native.

Once the message is received, you'll be able to get it with the `onMessage` prop. From there, you can do whatever you want, like using the `Linking` API of rn for instance.

It's a bit more tedious than you can expect, but at least, you can do absolutely anything you want, like using `data-actions` for the HTML to do whatever you want in your app.

I might expose a `onLinkPress` prop in the future, that might be more convenient for the majority of developers.

**Comment by LordVitor** [comment]
Thanks for reply, it works for me: 

`const _additionalScripts ="
(function() {
    var anchors = document.getElementsByTagName("a");
    for (var i = 0;i < anchors.length;i++) {
        anchors[i].addEventListener("click", function(event) {
            event.preventDefault();
            var _event = event.target.toString();
            window.WebViewBridge.send(JSON.stringify(_event))
        }) 
    }
}())
"`
```
const html = "<span>Hello World</span>";
<DisplayHTML
     htmlString={ html }
     additionalScripts={[ _additionalScripts ]}
     onMessage={(event)=> event.indexOf('http') === 0 ? Linking.openURL(event) : null }
 />
```
